Controllers/AlterarSenhaController.cs
using ControleDeContatos.Helper;
using ControleDeContatos.Models;
using ControleDeContatos.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace ControleDeContatos.Controllers
{
    public class AlterarSenhaController : Controller
    {
        private readonly IUsuarioRepositorio _usuarioRepositorio;
        private readonly Isessao _sessao;
        public AlterarSenhaController(IUsuarioRepositorio usuarioRepositorio, Isessao sessao)
        {
            _usuarioRepositorio = usuarioRepositorio;
            _sessao = sessao;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Alterar(AlterarSenhaModel alterarSenhaModel)
        {
            try
            {
                UsuarioModel usuarioLogado = _sessao.BuscarSessaoDoUsuario();
                alterarSenhaModel.Id = usuarioLogado.UsuarioId;
                if (ModelState.IsValid)
                {
                    _usuarioRepositorio.AlterarSenha(alterarSenhaModel);
                    TempData["MensagemSucesso"] = "Senha Alterada com Sucesso";
                    return View("Index", alterarSenhaModel);
                }
                return View("Index", alterarSenhaModel);
            }
            catch (System.Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos alterar sua senha, tente novamente, detalhe do erro: {erro.Message}";
                return View("Index", alterarSenhaModel);
            }
        }
    }
}

Views/AlterarSenha/Index.cshtml
@using ControleDeContatos.Enums
@model AlterarSenhaModel


@{
	ViewData["Title"] = "Alterar senha do usuário";
}

@if (TempData["MensagemSucesso"] != null)
{
	<div class="alert alert-success" role="alert">
		<button type="button" class="btn btn-sm close-alert" arial-label="Close">X</button>
		@TempData["MensagemSucesso"]
	</div>
}
@if (TempData["MensagemErro"] != null)
{
	<div class="alert alert-danger" role="alert">
		<button type="button" class="btn btn-sm close-alert" arial-label="Close">X</button>
		@TempData["MensagemErro"]
	</div>
}
<div class="text-center">
	<h1 class="display-4">Alterar Senha</h1>
	<br />
	<br />
	<form asp-controller="AlterarSenha" asp-action="Alterar" method="post">
		<div class="form-group text-start">
			<label for="senhaAtual" class="form-label">Senha Atual</label>
			<input type="password" asp-for="SenhaAtual" class="form-control" placeholder="Digite a senha atual do usuario"> 
			@Html.ValidationMessageFor(x => x.SenhaAtual)
		</div>
		<div class="form-group text-start">
			<label for="novaSenha" class="form-label">Nova Senha</label>
			<input type="password" asp-for="NovaSenha" class="form-control" placeholder="Digite a nova senha do usuario">
			@Html.ValidationMessageFor(x => x.NovaSenha)
		</div>
		<div class="form-group text-start">
			<label for="confirmarNovaSenha" class="form-label">Confirmar Nova Senha</label>
			<input type="password" asp-for="ConfirmarNovaSenha" class="form-control" placeholder="Confirme a nova senha do usuario">
			@Html.ValidationMessageFor(x => x.ConfirmarNovaSenha)
		</div>
		<br />
		<button type="submit" class="btn btn-success">Alterar</button>
		<div>
			
		<a class="btn btn-primary" asp-controller="Home" asp-action="Index">Voltar</a>
		</div>
	</form>
	
</div>